development: &default
  adapter: postgresql
  database: scrapper
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: scrapper_test

production:
  <<: *default
  database: scrapper_production